// nuxtjs-app/components/ChatWindow.vue
<script setup lang="ts">
import { toast } from 'vue-sonner';
import type { ChatMessage, ChatSession } from '~/types/chat';

const { loadSessions, saveSessions } = useChatStorage();

const sessions = ref<ChatSession[]>([]);
const activeSessionId = ref<string | null>(null);
const loading = ref(false);
const error = ref<string | null>(null);
const bottomRef = ref<HTMLElement | null>(null);

onMounted(() => {
  const saved = loadSessions();
  if (saved.length) {
    sessions.value = saved;
    activeSessionId.value = saved[0].id;
  } else {
    const initialSession: ChatSession = {
      id: crypto.randomUUID(),
      title: 'New Chat',
      messages: [],
      updatedAt: Date.now()
    };
    sessions.value = [initialSession];
    activeSessionId.value = initialSession.id;
  }

  // Keyboard Shortcuts
  const onKeyDown = (e: KeyboardEvent) => {
    if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
      e.preventDefault();
      document.querySelector('textarea')?.focus() || document.querySelector('input')?.focus();
      toast.info('Input focused' , { duration: 1000 });
    }
  };
  window.addEventListener('keydown', onKeyDown);
  onUnmounted(() => window.removeEventListener('keydown', onKeyDown));
});

watch(sessions, (newSessions) => {
  if (newSessions.length > 0) {
    saveSessions(newSessions);
  }
}, { deep: true });

watch([activeSessionId, loading], () => {
  nextTick(() => {
    bottomRef.value?.scrollIntoView({ behavior: 'smooth' });
  });
});

const activeSession = computed(() => 
  sessions.value.find(s => s.id === activeSessionId.value) || sessions.value[0]
);
const messages = computed(() => activeSession.value?.messages || []);

const updateActiveSession = (newMessages: ChatMessage[]) => {
  sessions.value = sessions.value.map(s => 
    s.id === activeSessionId.value 
      ? { 
          ...s, 
          messages: newMessages, 
          updatedAt: Date.now(),
          title: s.title === 'New Chat' && newMessages.length > 0 
            ? newMessages[0].content.slice(0, 30) + (newMessages[0].content.length > 30 ? '...' : '')
            : s.title
        } 
      : s
  );
};

const handleRenameSession = ({ id, title }: { id: string, title: string }) => {
  sessions.value = sessions.value.map(s => s.id === id ? { ...s, title } : s);
  toast.success('Session renamed');
};

const handleSend = async (content: string) => {
  if (!content.trim() || !activeSessionId.value) return;
  error.value = null;

  const userMsg: ChatMessage = {
    id: crypto.randomUUID(),
    role: 'user',
    content: content.trim(),
    timestamp: Date.now(),
  };

  const updatedMessages = [...messages.value, userMsg];
  updateActiveSession(updatedMessages);
  loading.value = true;

  try {
    const res = await fetch('/api/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt: content.trim(), history: messages.value.slice(-10) }),
    });

    if (!res.ok) {
      throw new Error('Request failed');
    }

    const reader = res.body?.getReader();
    if (!reader) throw new Error('No stream available');
    
    const decoder = new TextDecoder();
    let accumulated = '';
    const aiMsgId = crypto.randomUUID();
    let isFirstChunk = true;

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      accumulated += decoder.decode(value, { stream: true });

      let displayText = accumulated;
      try {
          const parsed = JSON.parse(accumulated);
          if (parsed.response) displayText = parsed.response;
      } catch {
          if (accumulated.startsWith('{"response":"')) {
              let stripped = accumulated.substring(13);
              if (stripped.endsWith('"}')) stripped = stripped.slice(0, -2);
              else if (stripped.endsWith('"')) stripped = stripped.slice(0, -1);
              stripped = stripped.replace(/\\n/g, '\n').replace(/\\"/g, '"');
              displayText = stripped;
          }
      }

      if (isFirstChunk) {
        loading.value = false;
        isFirstChunk = false;
      }

      const el = document.querySelector('.messages');
      const wasAtBottom = el ? (el.scrollHeight - el.scrollTop - el.clientHeight < 50) : true;
      const currentScrollTop = el ? el.scrollTop : 0;

      const activeIdx = sessions.value.findIndex(s => s.id === activeSessionId.value);
      if (activeIdx !== -1) {
        const session = sessions.value[activeIdx];
        const msgIdx = session.messages.findIndex(m => m.id === aiMsgId);
        if (msgIdx === -1) {
          session.messages.push({
            id: aiMsgId,
            role: 'ai',
            content: displayText,
            timestamp: Date.now()
          });
        } else {
          session.messages[msgIdx].content = displayText;
        }
        session.updatedAt = Date.now();
      }
      
      nextTick(() => { 
        if (el) {
          if (!wasAtBottom) {
            el.scrollTop = currentScrollTop;
          } else {
            bottomRef.value?.scrollIntoView({ behavior: 'instant' });
          }
        }
      });
    }
  } catch (err: any) {
    toast.error(err.message || 'Failed to send message');
    error.value = err.message;
    loading.value = false;
  }
};

const handleNewChat = () => {
  const newSession: ChatSession = {
    id: crypto.randomUUID(),
    title: 'New Chat',
    messages: [],
    updatedAt: Date.now()
  };
  sessions.value.unshift(newSession);
  activeSessionId.value = newSession.id;
  toast.success('New chat started');
};

const handleDeleteSession = (id: string) => {
  const remaining = sessions.value.filter(s => s.id !== id);
  sessions.value = remaining;
  if (activeSessionId.value === id) {
    activeSessionId.value = remaining[0]?.id || null;
    if (remaining.length === 0) {
      handleNewChat();
    }
  }
  toast.info('Chat session deleted');
};

const handleJump = (id: string) => {
  const el = document.getElementById(id);
  if (el) {
    el.scrollIntoView({ behavior: 'smooth', block: 'center' });
    el.classList.add('highlight-pulse');
    setTimeout(() => el.classList.remove('highlight-pulse'), 2000);
  }
};

const handleClear = () => {
  updateActiveSession([]);
  error.value = null;
  toast.info('Chat history cleared');
};
</script>

<template>
  <div class="container">
    <Sidebar 
      :sessions="sessions" 
      :activeId="activeSessionId" 
      @select="activeSessionId = $event"
      @new="handleNewChat"
      @delete="handleDeleteSession"
      @rename="handleRenameSession"
      @jump="handleJump"
    />

    <div class="wrapper">
      <header class="header">
        <div class="headerLeft">
          <div class="logo">
            <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
              <circle cx="14" cy="14" r="14" fill="url(#g1)"/>
              <path d="M8 14l4 4 8-8" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              <defs>
                <linearGradient id="g1" x1="0" y1="0" x2="28" y2="28" gradientUnits="userSpaceOnUse">
                  <stop stop-color="#7c6af7"/>
                  <stop offset="1" stop-color="#a78bfa"/>
                </linearGradient>
              </defs>
            </svg>
          </div>
          <div>
            <h1 class="title">Nexus AI</h1>
            <p class="subtitle">{{ activeSession?.title || 'New Chat' }} &bull; GPT-4o mini</p>
          </div>
        </div>
        <div class="headerRight">
          <span class="badge">
            <span class="dot" :style="{ background: loading ? 'var(--warning)' : 'var(--success)' }" />
            {{ loading ? 'Thinking...' : 'Online' }}
          </span>
          <button v-if="messages.length > 0" class="clearBtn" @click="handleClear">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="3 6 5 6 21 6"></polyline>
              <path d="M19 6l-1 14H6L5 6"></path>
              <path d="M10 11v6m4-6v6"></path>
              <path d="M9 6V4h6v2"></path>
            </svg>
            Clear
          </button>
        </div>
      </header>

      <main class="messages">
        <div v-if="messages.length === 0 && !loading" class="empty">
          <div class="emptyIcon">✦</div>
          <h2 class="emptyTitle">How can I help you today?</h2>
          <p class="emptyText">Ask me anything. Press <span class="kbd">⌘ K</span> to focus.</p>
          <div class="suggestGrid">
            <button v-for="s in ['Nuxt 3 vs Next.js', 'Vue 3 Composition API', 'SSR vs CSR']" :key="s" class="suggest" @click="handleSend(s)">
              {{ s }}
            </button>
          </div>
        </div>

        <MessageBubble v-for="msg in messages" :key="msg.id" :message="msg" />
        <TypingIndicator v-if="loading" />
        <div v-if="error" class="errorBanner">⚠️ {{ error }}</div>
        <div ref="bottomRef" />
      </main>

      <ChatInput :disabled="loading" @send="handleSend" />
    </div>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  height: 100vh;
  width: 100vw;
  overflow: hidden;
  background: var(--bg-primary);
}

.wrapper {
  display: flex;
  flex-direction: column;
  flex: 1;
  height: 100vh;
  max-width: 1000px;
  margin: 0 auto;
  padding: 0 1.5rem;
  position: relative;
}

.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem 0;
  border-bottom: 1px solid var(--border-subtle);
  flex-shrink: 0;
  gap: 1rem;
}
.headerLeft { display: flex; align-items: center; gap: 0.75rem; }
.headerRight { display: flex; align-items: center; gap: 0.75rem; }


.logo {
  display: flex;
  align-items: center;
  filter: drop-shadow(0 0 10px rgba(124, 106, 247, 0.5));
}

.title { 
  font-size: 1.1rem; 
  font-weight: 700; 
  color: var(--text-primary);
  letter-spacing: -0.02em;
}
.subtitle { font-size: 0.72rem; color: var(--text-muted); margin-top: 1px; }

.badge {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.72rem;
  color: var(--text-secondary);
  background: var(--bg-card);
  border: 1px solid var(--border-subtle);
  padding: 4px 10px;
  border-radius: 999px;
}
.dot { 
  width: 7px; 
  height: 7px; 
  border-radius: 50%; 
  animation: pulse 2s infinite;
}

.clearBtn {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.75rem;
  background: var(--bg-card);
  border: 1px solid var(--border-subtle);
  padding: 6px 12px;
  border-radius: var(--radius-sm);
  cursor: pointer;
  color: var(--text-secondary);
  transition: all 0.2s;
}
.clearBtn:hover { 
  color: var(--error); 
  border-color: var(--error);
  background: rgba(255, 87, 87, 0.08);
}

.messages {
  flex: 1;
  overflow-y: auto;
  min-height: 0;
  padding: 1.5rem 0 1rem;
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  scroll-behavior: smooth;
}

.empty {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 2rem 1rem;
  animation: fadeIn 0.5s ease;
}
.emptyIcon { 
  font-size: 2.5rem; 
  color: var(--accent-primary); 
  margin-bottom: 1rem; 
  filter: drop-shadow(0 0 12px var(--accent-primary));
}
.emptyTitle { font-size: 1.4rem; font-weight: 600; margin-bottom: 0.5rem; }
.emptyText { color: var(--text-secondary); font-size: 0.9rem; margin-bottom: 2rem; }

.kbd {
  background: var(--bg-tertiary);
  border: 1px solid var(--border-subtle);
  padding: 2px 4px;
  border-radius: 4px;
  font-family: inherit;
  font-size: 0.75rem;
}

.suggestGrid { display: grid; grid-template-columns: 1fr 1fr; gap: 0.6rem; width: 100%; max-width: 540px; }
.suggest {
  background: var(--bg-card);
  border: 1px solid var(--border-subtle);
  padding: 0.75rem 1rem;
  border-radius: var(--radius-md);
  color: var(--text-secondary);
  cursor: pointer;
  text-align: left;
  transition: all 0.2s;
  line-height: 1.4;
  font-size: 0.82rem;
  font-family: inherit;
}
.suggest:hover { 
  border-color: var(--border-accent); 
  color: var(--text-primary); 
  background: var(--bg-tertiary);
  transform: translateY(-1px);
}

.errorBanner {
  background: rgba(255,87,87,0.1);
  border: 1px solid rgba(255,87,87,0.3);
  color: var(--error);
  padding: 0.75rem 1rem;
  border-radius: var(--radius-sm);
  font-size: 0.85rem;
  margin-top: 0.5rem;
  animation: fadeInUp 0.3s ease;
}

@media (max-width: 480px) {
  .suggestGrid { grid-template-columns: 1fr; }
  .title { font-size: 0.95rem; }
  .clearBtn span { display: none; }
}
</style>

// angular-app/src/app/components/chat-window/chat-window.component.ts
import { Component, OnInit, ViewChild, ElementRef, inject, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef } from '@angular/core';
import { LucideAngularModule, Trash2 } from 'lucide-angular';
import { ChatService } from '../../services/chat.service';
import { ToastService } from '../../services/toast.service';
import { MessageBubbleComponent } from '../message-bubble/message-bubble.component';
import { ChatInputComponent } from '../chat-input/chat-input.component';
import { SkeletonLoaderComponent } from '../skeleton-loader/skeleton-loader.component';
import { SidebarComponent } from '../sidebar/sidebar.component';
import { ChatMessage, ChatSession } from '../../types/chat';

@Component({
  selector: 'app-chat-window',
  standalone: true,
  imports: [CommonModule, MessageBubbleComponent, ChatInputComponent, SkeletonLoaderComponent, SidebarComponent, LucideAngularModule],
  templateUrl: './chat-window.component.html',
  styleUrl: './chat-window.component.css'
})
export class ChatWindowComponent implements OnInit {
  sessions: ChatSession[] = [];
  activeSessionId: string | null = null;
  loading = false;
  error: string | null = null;
  streamingMessageId: string | null = null;

  private storageKey = 'nexus_chat_sessions_angular';
  private chatService = inject(ChatService);
  private toastService = inject(ToastService);
  private cdr = inject(ChangeDetectorRef);
  private scrollRafId: number | null = null;

  @ViewChild('scrollContainer') private scrollContainer!: ElementRef<HTMLElement>;

  @HostListener('window:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) {
    if ((event.ctrlKey || event.metaKey) && event.key === 'k') {
      event.preventDefault();
      const input = document.querySelector('textarea') || document.querySelector('input');
      (input as HTMLElement)?.focus();
      this.toastService.info('Input focused');
    }
  }

  ngOnInit() {
    this.loadSessions();
    this.cdr.detectChanges();
  }

  get activeSession(): ChatSession | undefined {
    return this.sessions.find(s => s.id === this.activeSessionId) || this.sessions[0];
  }

  get messages(): ChatMessage[] {
    return this.activeSession?.messages || [];
  }

  isMessageStreaming(msgId: string): boolean {
    return this.streamingMessageId === msgId;
  }

  handleSend(content: string) {
    if (!content.trim() || !this.activeSessionId) return;

    const userMsg: ChatMessage = {
      id: crypto.randomUUID(),
      role: 'user',
      content: content.trim(),
      timestamp: Date.now()
    };

    const updatedMessages = [...this.messages, userMsg];
    this.updateActiveSession(updatedMessages);
    this.loading = true;
    this.error = null;
    this.cdr.detectChanges();

    this.scheduleScroll(true);

    const aiMsgId = crypto.randomUUID();
    let isFirstChunk = true;

    this.chatService.sendMessage(content, this.messages.slice(-10)).subscribe({
      next: (accumulated) => {
        const el = this.scrollContainer?.nativeElement;
        const wasAtBottom = el ? (el.scrollHeight - el.scrollTop - el.clientHeight < 50) : true;
        const currentScrollTop = el ? el.scrollTop : 0;

        if (isFirstChunk) {
          this.loading = false;
          this.streamingMessageId = aiMsgId;
          isFirstChunk = false;
          this.cdr.detectChanges();
        }

        const aiMsg: ChatMessage = {
          id: aiMsgId,
          role: 'ai',
          content: accumulated,
          timestamp: Date.now()
        };

        const currentMessages = this.activeSession?.messages || [];
        const existingIdx = currentMessages.findIndex(m => m.id === aiMsgId);

        if (existingIdx === -1) {
          this.updateActiveSession([...updatedMessages, aiMsg]);
        } else {
          const updatedWithAi = [...currentMessages];
          updatedWithAi[existingIdx] = aiMsg;
          this.updateActiveSession(updatedWithAi);
        }

        this.cdr.detectChanges();

        if (el) {
          if (!wasAtBottom) {
            el.scrollTop = currentScrollTop;
          } else {
            el.scrollTop = el.scrollHeight;
          }
        }
      },
      error: (err) => {
        const msg = err.message || 'Error occurred';
        this.toastService.error(msg);
        this.error = msg;
        this.loading = false;
        this.streamingMessageId = null;
        this.cdr.detectChanges();
      },
      complete: () => {
        this.loading = false;
        this.streamingMessageId = null;
        this.scheduleScroll();
        this.cdr.detectChanges();
      }
    });
  }

  handleNewChat() {
    const newSession: ChatSession = {
      id: crypto.randomUUID(),
      title: 'New Chat',
      messages: [],
      updatedAt: Date.now()
    };
    this.sessions.unshift(newSession);
    this.activeSessionId = newSession.id;
    this.saveSessions();
    this.toastService.success('New chat started');
    this.cdr.detectChanges();
  }

  handleSelectSession(id: string) {
    this.activeSessionId = id;
    this.cdr.detectChanges();
    setTimeout(() => this.scrollToBottom(false), 50);
  }

  handleDeleteSession(id: string) {
    this.sessions = this.sessions.filter(s => s.id !== id);
    if (this.activeSessionId === id) {
      this.activeSessionId = this.sessions[0]?.id || null;
      if (this.sessions.length === 0) {
        this.handleNewChat();
      }
    }
    this.saveSessions();
    this.toastService.info('Chat session deleted');
    this.cdr.detectChanges();
  }

  handleRenameSession(event: { id: string, title: string }) {
    this.sessions = this.sessions.map(s => s.id === event.id ? { ...s, title: event.title } : s);
    this.saveSessions();
    this.toastService.success('Session renamed');
    this.cdr.detectChanges();
  }

  handleJump(id: string) {
    const targetSession = this.sessions.find(s => s.messages.some(m => m.id === id));
    if (targetSession && this.activeSessionId !== targetSession.id) {
      this.handleSelectSession(targetSession.id);
    }

    setTimeout(() => {
      const el = document.getElementById(id);
      if (el) {
        el.scrollIntoView({ behavior: 'smooth', block: 'center' });
        el.classList.add('highlight-pulse');
        setTimeout(() => el.classList.remove('highlight-pulse'), 2000);
      }
    }, 120);
  }

  handleClear() {
    this.updateActiveSession([]);
    this.error = null;
    this.toastService.info('Chat history cleared');
    this.cdr.detectChanges();
  }

  private scheduleScroll(smooth = false) {
    if (this.scrollRafId !== null) cancelAnimationFrame(this.scrollRafId);
    this.scrollRafId = requestAnimationFrame(() => {
      this.scrollToBottom(smooth);
      this.scrollRafId = null;
    });
  }

  private scrollToBottom(smooth = false) {
    try {
      const el = this.scrollContainer.nativeElement;
      if (smooth) {
        el.scrollTo({ top: el.scrollHeight, behavior: 'smooth' });
      } else {
        el.scrollTop = el.scrollHeight;
      }
    } catch (err) {}
  }

  private updateActiveSession(newMessages: ChatMessage[]) {
    this.sessions = this.sessions.map(s =>
      s.id === this.activeSessionId
        ? {
            ...s,
            messages: newMessages,
            updatedAt: Date.now(),
            title: s.title === 'New Chat' && newMessages.length > 0
              ? newMessages[0].content.slice(0, 30) + (newMessages[0].content.length > 30 ? '...' : '')
              : s.title
          }
        : s
    );
    this.saveSessions();
  }

  private loadSessions() {
    const raw = localStorage.getItem(this.storageKey);
    if (raw) {
      this.sessions = JSON.parse(raw);
      this.activeSessionId = this.sessions[0]?.id || null;
      setTimeout(() => this.scrollToBottom(false), 50);
    } else {
      this.handleNewChat();
    }
  }

  private saveSessions() {
    localStorage.setItem(this.storageKey, JSON.stringify(this.sessions));
  }
}

<div class="container">
  <app-sidebar 
    [sessions]="sessions" 
    [activeId]="activeSessionId" 
    (select)="handleSelectSession($event)"
    (newChat)="handleNewChat()"
    (delete)="handleDeleteSession($event)"
    (rename)="handleRenameSession($event)"
    (jump)="handleJump($event)"
  ></app-sidebar>

  <div class="wrapper">
    <header class="header">
      <div class="headerLeft">
        <div class="logo">
          <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
            <circle cx="14" cy="14" r="14" fill="url(#g1)"/>
            <path d="M8 14l4 4 8-8" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <defs>
              <linearGradient id="g1" x1="0" y1="0" x2="28" y2="28" gradientUnits="userSpaceOnUse">
                <stop stop-color="#7c6af7"/>
                <stop offset="1" stop-color="#a78bfa"/>
              </linearGradient>
            </defs>
          </svg>
        </div>
        <div>
          <h1 class="title">Nexus AI</h1>
          <p class="subtitle">{{ activeSession?.title || 'New Chat' }} &bull; GPT-4o mini</p>
        </div>
      </div>
      <div class="headerRight">
        <span class="badge">
          <span class="dot" [style.background]="loading ? 'var(--error)' : 'var(--success)'"></span>
          {{ loading ? 'Thinking...' : 'Online' }}
        </span>
        @if (messages.length > 0) {
          <button class="clearBtn" (click)="handleClear()">
            <lucide-icon name="trash-2" [size]="16"></lucide-icon>
            Clear
          </button>
        }
      </div>
    </header>

    <main class="messages" #scrollContainer>
      @if (messages.length === 0 && !loading) {
        <div class="empty">
          <div class="emptyIcon">✦</div>
          <h2 class="emptyTitle">How can I help you today?</h2>
          <p class="emptyText">Ask me anything. Press <span class="kbd">⌘ K</span> to focus.</p>
          <div class="suggestGrid">
            @for (s of ['Nuxt 3 vs Next.js', 'Vue 3 Composition API', 'SSR vs CSR']; track s) {
              <button class="suggest" (click)="handleSend(s)">{{ s }}</button>
            }
          </div>
        </div>
      }

      @for (msg of messages; track msg.id) {
        <app-message-bubble [message]="msg" [isStreaming]="isMessageStreaming(msg.id)"></app-message-bubble>
      }

      @if (loading) {
        <app-skeleton-loader></app-skeleton-loader>
      }

      @if (error) {
        <div class="errorBanner">⚠️ {{ error }}</div>
      }
    </main>

    <app-chat-input [disabled]="loading" (send)="handleSend($event)"></app-chat-input>
  </div>
</div>
