// nextjs-app/src/components/ChatInput.tsx
'use client';
import { useState, useRef, useCallback, KeyboardEvent } from 'react';
import styles from './ChatInput.module.css';

interface Props {
  onSend: (value: string) => void;
  disabled: boolean;
}

const MAX_CHARS = 2000;

export default function ChatInput({ onSend, disabled }: Props) {
  const [value, setValue] = useState('');
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const autoResize = useCallback(() => {
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 180) + 'px';
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    if (e.target.value.length > MAX_CHARS) return;
    setValue(e.target.value);
    autoResize();
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      submit();
    }
  };

  const submit = useCallback(() => {
    const trimmed = value.trim();
    if (!trimmed || disabled) return;
    onSend(trimmed);
    setValue('');
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.focus();
    }
  }, [value, disabled, onSend]);

  const pct = (value.length / MAX_CHARS) * 100;
  const nearLimit = value.length > MAX_CHARS * 0.85;

  return (
    <footer className={styles.footer}>
      <form
        className={styles.form}
        onSubmit={(e) => { e.preventDefault(); submit(); }}
        aria-label="Chat input form"
      >
        <div className={`${styles.inputBox} ${disabled ? styles.inputBoxDisabled : ''}`}>
          <textarea
            ref={textareaRef}
            id="chat-input"
            className={styles.textarea}
            value={value}
            onChange={handleChange}
            onKeyDown={handleKeyDown}
            placeholder="Ask anything… (Shift+Enter for new line)"
            rows={1}
            disabled={disabled}
            aria-label="Chat message input"
            aria-describedby="char-count"
          />

          {/* Progress ring when near limit */}
          {nearLimit && (
            <span id="char-count" className={styles.charCount} aria-label={`${value.length} of ${MAX_CHARS} characters used`}>
              {MAX_CHARS - value.length}
            </span>
          )}

          <button
            type="submit"
            className={`${styles.sendBtn} ${(!value.trim() || disabled) ? styles.sendBtnDisabled : styles.sendBtnActive}`}
            disabled={!value.trim() || disabled}
            aria-label="Send message"
          >
            {disabled ? (
              <span className={styles.spinner} aria-hidden="true" />
            ) : (
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                <path d="M22 2L11 13" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                <path d="M22 2L15 22 11 13 2 9l20-7z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            )}
          </button>
        </div>

        {/* Progress bar */}
        <div
          className={styles.progress}
          style={{ width: `${pct}%`, opacity: nearLimit ? 1 : 0 }}
          role="progressbar"
          aria-valuenow={value.length}
          aria-valuemax={MAX_CHARS}
        />

        <p className={styles.hint}>
          Press <kbd>Enter</kbd> to send · <kbd>Shift+Enter</kbd> for new line
        </p>
      </form>
    </footer>
  );
}

// angular-app/src/app/components/chat-input/chat-input.component.ts
import { Component, EventEmitter, Input, Output, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Send } from 'lucide-angular';

@Component({
  selector: 'app-chat-input',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './chat-input.component.html',
  styleUrl: './chat-input.component.css'
})
export class ChatInputComponent {
  @Input() disabled = false;
  @Output() send = new EventEmitter<string>();
  @ViewChild('textarea') textarea!: ElementRef<HTMLTextAreaElement>;

  content = '';
  MAX_CHARS = 2000;

  handleInput(e: Event) {
    const target = e.target as HTMLTextAreaElement;
    if (target.value.length > this.MAX_CHARS) {
      target.value = target.value.substring(0, this.MAX_CHARS);
    }
    this.content = target.value;
    this.autoResize();
  }

  handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      this.submit();
    }
  }

  submit() {
    const trimmed = this.content.trim();
    if (!trimmed || this.disabled) return;
    this.send.emit(trimmed);
    this.content = '';
    this.textarea.nativeElement.value = '';
    this.autoResize();
  }

  private autoResize() {
    const el = this.textarea.nativeElement;
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 180) + 'px';
  }

  get pct() {
    return (this.content.length / this.MAX_CHARS) * 100;
  }

  get nearLimit() {
    return this.content.length > this.MAX_CHARS * 0.85;
  }
}

<footer class="footer">
  <form class="form" (submit)="$event.preventDefault(); submit()" aria-label="Chat input form">
    <div [class]="'inputBox' + (disabled ? ' inputBoxDisabled' : '')">
      <textarea
        #textarea
        id="chat-input"
        class="textarea"
        placeholder="Ask anything… (Shift+Enter for new line)"
        rows="1"
        [disabled]="disabled"
        (input)="handleInput($event)"
        (keydown)="handleKeyDown($event)"
        aria-label="Chat message input"
      ></textarea>

      <span *ngIf="nearLimit" class="charCount" aria-live="polite">
        {{ MAX_CHARS - content.length }}
      </span>

      <button
        type="submit"
        [class]="'sendBtn ' + (content.trim() && !disabled ? 'sendBtnActive' : 'sendBtnDisabled')"
        [disabled]="!content.trim() || disabled"
        aria-label="Send message"
      >
        <span *ngIf="disabled" class="spinner" aria-hidden="true"></span>
        <lucide-icon *ngIf="!disabled" name="send" [size]="18" aria-hidden="true"></lucide-icon>
      </button>
    </div>

    <div *ngIf="nearLimit" class="progressWrapper">
      <div
        class="progress"
        [style.width.%]="pct"
        role="progressbar"
        [ariaValueNow]="pct"
        [ariaValueMin]="0"
        [ariaValueMax]="100"
      ></div>
    </div>

    <p class="hint">
      Press <kbd>Enter</kbd> to send · <kbd>Shift+Enter</kbd> for new line
    </p>
  </form>
</footer>
