// nextjs-app/src/components/SkeletonLoader.tsx
import styles from './SkeletonLoader.module.css';

export default function SkeletonLoader() {
  return (
    <div className={`${styles.wrapper} animate-in`} role="status" aria-label="AI is responding">
      <div className={styles.avatar}>✦</div>
      <div className={styles.card}>
        <div className={styles.lines}>
          <div className={`${styles.line} ${styles.long}`} />
          <div className={`${styles.line} ${styles.medium}`} />
          <div className={`${styles.line} ${styles.short}`} />
        </div>
        <div className={styles.typing}>
          <span />
          <span />
          <span />
        </div>
      </div>
    </div>
  );
}

// angular-app/src/app/components/skeleton-loader/skeleton-loader.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-skeleton-loader',
  standalone: true,
  templateUrl: './skeleton-loader.component.html',
  styleUrl: './skeleton-loader.component.css'
})
export class SkeletonLoaderComponent {}

<div class="wrapper animate-in" role="status" aria-label="AI is responding">
  <div class="avatar">✦</div>
  <div class="card">
    <div class="lines">
      <div class="line long"></div>
      <div class="line medium"></div>
      <div class="line short"></div>
    </div>
    <div class="typing">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>
</div>
