// nextjs-app/src/components/MessageBubble.tsx
'use client';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { toast } from 'sonner';
import type { ChatMessage } from '@/types/chat';
import styles from './MessageBubble.module.css';

interface Props {
  message: ChatMessage;
}

export default function MessageBubble({ message }: Props) {
  const isUser = message.role === 'user';
  const time = new Date(message.timestamp).toLocaleTimeString([], {
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <div id={message.id} className={`${styles.wrapper} ${isUser ? styles.userWrapper : styles.aiWrapper} animate-in`}>
      {!isUser && (
        <div className={styles.avatar} aria-hidden="true">✦</div>
      )}
      <div className={`${styles.bubble} ${isUser ? styles.userBubble : styles.aiBubble} ${message.isError ? styles.errorBubble : ''}`}>
        {isUser ? (
          <p className={styles.userText}>{message.content}</p>
        ) : (
          <div className="markdown-body">
            <ReactMarkdown 
              remarkPlugins={[remarkGfm]}
              components={{
                code({ node, inline, className, children, ...props }: any) {
                  const match = /language-(\w+)/.exec(className || '');
                  const codeValue = String(children).replace(/\n$/, '');
                  
                  if (!inline && match) {
                    return (
                      <div className={styles.codeWrapper}>
                        <div className={styles.codeHeader}>
                          <span className={styles.codeLang}>{match[1]}</span>
                          <button 
                            className={styles.copyBtn}
                            onClick={() => {
                              navigator.clipboard.writeText(codeValue);
                              toast.success('Copied to clipboard');
                            }}
                          >
                            Copy
                          </button>
                        </div>
                        <code className={className} {...props}>
                          {children}
                        </code>
                      </div>
                    );
                  }
                  return <code className={className} {...props}>{children}</code>;
                }
              }}
            >
              {message.content}
            </ReactMarkdown>
          </div>
        )}
        <time className={styles.time} dateTime={new Date(message.timestamp).toISOString()}>
          {time}
        </time>
      </div>
      {isUser && (
        <div className={styles.avatarUser} aria-hidden="true">U</div>
      )}
    </div>
  );
}

// angular-app/src/app/components/message-bubble/message-bubble.component.ts
import { Component, Input, OnChanges, Directive, ElementRef, AfterViewChecked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MarkdownModule } from 'ngx-markdown';
import { ToastService } from '../../services/toast.service';

@Directive({
  selector: '[injectCopy]',
  standalone: true
})
export class InjectCopyDirective implements AfterViewChecked {
  constructor(
    private el: ElementRef,
    private toastService: ToastService
  ) {}

  ngAfterViewChecked() {
    const pres = this.el.nativeElement.querySelectorAll('pre');
    pres.forEach((pre: HTMLElement) => {
      if (!pre.querySelector('.custom-copy-btn')) {
        pre.style.position = 'relative';
        
        const btn = document.createElement('button');
        btn.className = 'custom-copy-btn';
        btn.innerHTML = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" class="copy-icon" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>';
        
        btn.onclick = () => {
          const code = pre.querySelector('code')?.innerText || '';
          navigator.clipboard.writeText(code);
          btn.classList.add('copied');
          btn.innerHTML = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" class="copy-icon text-success" stroke="#22c55e" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>';
          this.toastService.success('Copied to clipboard');
          
          setTimeout(() => {
            btn.classList.remove('copied');
            btn.innerHTML = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" class="copy-icon" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>';
          }, 2000);
        };
        
        pre.appendChild(btn);
      }
    });
  }
}

@Component({
  selector: 'app-message-bubble',
  standalone: true,
  imports: [CommonModule, MarkdownModule, InjectCopyDirective],
  templateUrl: './message-bubble.component.html',
  styleUrl: './message-bubble.component.css'
})
export class MessageBubbleComponent implements OnChanges {
  @Input() message: any;
  @Input() isStreaming = false;  // true while this specific message is still being streamed
  isUser = false;
  time = '';

  ngOnChanges() {
    this.isUser = this.message.role === 'user';
    this.time = new Date(this.message.timestamp).toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit'
    });
  }
}

<div [id]="message.id" [class]="'wrapper ' + (isUser ? 'userWrapper' : 'aiWrapper') + ' animate-in'">
  <div *ngIf="!isUser" class="avatar" aria-hidden="true">✦</div>
  <div [class]="'bubble ' + (isUser ? 'userBubble' : 'aiBubble') + (message.isError ? ' errorBubble' : '')">
    <div *ngIf="isUser" class="userText">{{ message.content }}</div>
    <div *ngIf="!isUser" class="markdown-body" injectCopy [class.is-streaming]="isStreaming">
      <markdown [data]="isStreaming ? message.content + ' ▋' : message.content"></markdown>
    </div>
    <time class="time" [attr.datetime]="message.timestamp | date:'yyyy-MM-ddTHH:mm:ss'">{{ time }}</time>
  </div>
  <div *ngIf="isUser" class="avatarUser" aria-hidden="true">U</div>
</div>
