// angular-app/src/app/components/sidebar/sidebar.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ChatSession } from '../../types/chat';
import { 
  LucideAngularModule, 
  Plus, 
  MessageSquare, 
  Trash2, 
  Hash, 
  Edit3, 
  Check, 
  X, 
  ChevronDown, 
  ChevronRight 
} from 'lucide-angular';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [
    CommonModule, 
    LucideAngularModule
  ],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.css'
})
export class SidebarComponent {
  @Input() sessions: ChatSession[] = [];
  @Input() activeId: string | null = null;
  @Output() select = new EventEmitter<string>();
  @Output() newChat = new EventEmitter<void>();
  @Output() delete = new EventEmitter<string>();
  @Output() jump = new EventEmitter<string>();
  @Output() rename = new EventEmitter<{ id: string, title: string }>();

  editingId: string | null = null;
  editValue = '';
  expandedSessions: Record<string, boolean> = {};

  toggleSessionOutline(id: string) {
    this.expandedSessions[id] = !this.expandedSessions[id];
  }

  sortedSessions() {
    return [...this.sessions].sort((a, b) => b.updatedAt - a.updatedAt);
  }

  getPrompts(session: ChatSession) {
    return session.messages.filter(m => m.role === 'user');
  }

  handleDelete(event: MouseEvent, id: string) {
    event.stopPropagation();
    this.delete.emit(id);
  }

  startEditing(event: MouseEvent, session: ChatSession) {
    event.stopPropagation();
    this.editingId = session.id;
    this.editValue = session.title;
  }

  onInputChange(value: string) {
    this.editValue = value;
  }

  saveEdit() {
    if (this.editingId && this.editValue.trim()) {
      this.rename.emit({ id: this.editingId, title: this.editValue.trim() });
    }
    this.editingId = null;
  }
}

<aside class="sidebar">
  <div class="sidebarHeader">
    <button class="newChatBtn" (click)="newChat.emit()">
      <lucide-icon name="plus" [size]="18"></lucide-icon>
      <span>New Chat</span>
    </button>
  </div>

  <div class="history">
    <div class="historyHeader">
      <h3 class="label">History</h3>
    </div>
    @if (sessions.length === 0) {
      <div class="empty">No threads yet</div>
    } @else {
      <div class="list">
        @for (session of sortedSessions(); track session.id) {
          <div class="item-wrapper">
            <div 
              class="item" 
              [class.active]="activeId === session.id"
              (click)="select.emit(session.id)"
            >
              <div class="itemMain">
                <button class="expandBtn" (click)="$event.stopPropagation(); toggleSessionOutline(session.id)">
                  <lucide-icon 
                    [name]="(expandedSessions[session.id] || (activeId === session.id)) ? 'chevron-down' : 'chevron-right'" 
                    [size]="14"
                  ></lucide-icon>
                </button>
                <lucide-icon name="message-square" [size]="16" class="msgIcon"></lucide-icon>
                
                @if (editingId === session.id) {
                  <div class="editGroup" (click)="$event.stopPropagation()">
                    <input 
                      #renameInput
                      class="renameInput" 
                      [value]="editValue" 
                      (input)="onInputChange(renameInput.value)"
                      (keydown.enter)="saveEdit()"
                      (keydown.escape)="editingId = null"
                      autofocus
                    />
                    <button class="iconBtn" (click)="saveEdit()"><lucide-icon name="check" [size]="14"></lucide-icon></button>
                  </div>
                } @else {
                  <span class="itemTitle">{{ session.title }}</span>
                }
              </div>

              <div *ngIf="editingId !== session.id" class="actions">
                <button class="actionBtn" (click)="startEditing($event, session)" title="Rename">
                  <lucide-icon name="edit-3" [size]="14"></lucide-icon>
                </button>
                <button class="actionBtn delete" (click)="handleDelete($event, session.id)" title="Delete">
                  <lucide-icon name="trash-2" [size]="14"></lucide-icon>
                </button>
              </div>
            </div>

            @if ((expandedSessions[session.id] || (activeId === session.id)) && getPrompts(session).length > 0 && editingId !== session.id) {
              <div class="outline">
                @for (prompt of getPrompts(session); track prompt.id) {
                  <button class="outlineItem" (click)="jump.emit(prompt.id)">
                    <lucide-icon name="hash" [size]="12"></lucide-icon>
                    <span class="outlineText">{{ prompt.content }}</span>
                  </button>
                }
              </div>
            }
          </div>
        }
      </div>
    }
  </div>
</aside>

// nextjs-app/src/components/Sidebar.tsx
'use client';
import { useState } from 'react';
import { Plus, MessageSquare, Trash2, Hash, Edit3, Check, X, PanelLeftClose, ChevronDown, ChevronRight } from 'lucide-react';
import type { ChatSession } from '@/types/chat';
import styles from './Sidebar.module.css';

interface Props {
  sessions: ChatSession[];
  activeId: string | null;
  onSelect: (id: string) => void;
  onNew: () => void;
  onDelete: (id: string, e: React.MouseEvent) => void;
  onRename: (id: string, newTitle: string) => void;
  onJump?: (messageId: string) => void;
}

export default function Sidebar({ sessions, activeId, onSelect, onNew, onDelete, onRename, onJump }: Props) {
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editValue, setEditValue] = useState('');
  const [expandedSessions, setExpandedSessions] = useState<Record<string, boolean>>({});

  const toggleSessionOutline = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setExpandedSessions(prev => ({ ...prev, [id]: !prev[id] }));
  };

  const startEditing = (id: string, title: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setEditingId(id);
    setEditValue(title);
  };

  const saveEdit = (e: React.MouseEvent | React.KeyboardEvent) => {
    e.stopPropagation();
    if (editingId && editValue.trim()) {
      onRename(editingId, editValue.trim());
    }
    setEditingId(null);
  };

  return (
    <aside className={styles.sidebar}>
      <div className={styles.sidebarHeader}>
        <button className={styles.newChatBtn} onClick={onNew}>
          <Plus size={18} />
          <span>New Chat</span>
        </button>
      </div>

      <div className={styles.history}>
        <div className={styles.historyHeader}>
          <h3 className={styles.label}>History</h3>
        </div>
        {sessions.length === 0 ? (
          <p className={styles.empty}>No threads yet</p>
        ) : (
          <div className={styles.list}>
            {sessions
              .sort((a, b) => b.updatedAt - a.updatedAt)
              .map(session => {
                const isExpanded = expandedSessions[session.id] ?? (activeId === session.id);
                const userPrompts = session.messages.filter(m => m.role === 'user');

                return (
                  <div key={session.id} className={styles.itemWrapper}>
                    <div
                      className={`${styles.item} ${activeId === session.id ? styles.active : ''}`}
                      onClick={() => onSelect(session.id)}
                    >
                      <div className={styles.itemMain}>
                        <button 
                          className={styles.expandBtn}
                          onClick={(e) => toggleSessionOutline(session.id, e)}
                        >
                          {isExpanded ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                        </button>
                        <MessageSquare size={16} className={styles.msgIcon} />
                        
                        {editingId === session.id ? (
                          <div className={styles.editGroup}>
                            <input
                              autoFocus
                              className={styles.renameInput}
                              value={editValue}
                              onChange={(e) => setEditValue(e.target.value)}
                              onKeyDown={(e) => e.key === 'Enter' && saveEdit(e)}
                              onClick={(e) => e.stopPropagation()}
                            />
                            <button className={styles.iconBtn} onClick={saveEdit}><Check size={14} /></button>
                          </div>
                        ) : (
                          <span className={styles.itemTitle}>{session.title}</span>
                        )}
                      </div>

                      {!editingId && (
                        <div className={styles.actions}>
                          <button
                            className={styles.actionBtn}
                            onClick={(e) => startEditing(session.id, session.title, e)}
                            title="Rename"
                          >
                            <Edit3 size={14} />
                          </button>
                          <button
                            className={styles.actionBtn}
                            onClick={(e) => onDelete(session.id, e)}
                            aria-label="Delete session"
                          >
                            <Trash2 size={14} />
                          </button>
                        </div>
                      )}
                    </div>

                    {/* Messages Outline (Collapsible) */}
                    {isExpanded && userPrompts.length > 0 && !editingId && (
                      <div className={styles.outline}>
                        {userPrompts.slice(0, 5).map(prompt => (
                          <button 
                            key={prompt.id} 
                            className={styles.outlineItem}
                            onClick={() => onJump?.(prompt.id)}
                          >
                            <Hash size={12} />
                            <span className={styles.outlineText}>{prompt.content}</span>
                          </button>
                        ))}
                        {userPrompts.length > 5 && <span className={styles.more}>& more...</span>}
                      </div>
                    )}
                  </div>
                );
              })}
          </div>
        )}
      </div>
    </aside>
  );
}
